# Setup eigen3
IF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
  INCLUDE_DIRECTORIES(/usr/include/eigen3)
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")

IF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  INCLUDE_DIRECTORIES(/usr/local/include/eigen3)
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
