
IF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  INCLUDE_DIRECTORIES ( /System/Library/Frameworks )
    FIND_LIBRARY(GL_LIBRARIES OpenGL )
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")

IF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
  FIND_LIBRARY(GL_LIBRARIES GL )
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
