# Set version of the main app
FUNCTION (cm8kr_set_version MINOR MAJOR PATCH)
  set( MAJOR_VERSION ${MINOR} CACHE STRING "Major Version")
  set( MINOR_VERSION ${MAJOR} CACHE STRING "Minor Version")
  set( PATCH_VERSION ${PATCH} CACHE STRING "Patch Version")
  set( VERSION_STRING "${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}" CACHE STRING "Version String")
  add_definitions(-D${CM8KR_PROJECT_NAME_UPPER}_VERSION_STRING="${VERSION_STRING}"
    -D${CM8KR_PROJECT_NAME_UPPER}_MAJOR_VERSION="${MAJOR_VERSION}"
    -D${CM8KR_PROJECT_NAME_UPPER}_MINOR_VERSION="${MINOR_VERSION}"
    -D${CM8KR_PROJECT_NAME_UPPER}_PATCH_VERSION="${PATCH_VERSION}"
  )
  MESSAGE(STATUS "${CMAKE_PROJECT_NAME} ${VERSION_STRING}")
ENDFUNCTION()
